services:
  - type: web
    name: discovery-server
    runtime: image
    image:
      url: docker.io/jefersonalexander/discovery-server:latest
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
    autoDeploy: false

  - type: web
    name: microservice-authentication
    runtime: image
    image:
      url: docker.io/jefersonalexander/microservice-authentication:latest
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URI
        value: https://discovery-server.onrender.com/eureka
      - key: JWT_SECRET
        fromSecret: ${jwt-secret}
      - key: JWT_EXPIRATION
        fromSecret: ${jwt-expiration}
      - key: SPRING_DATASOURCE_URL
        fromSecret: ${auth-db-url}
      - key: SPRING_DATASOURCE_USERNAME
        fromSecret: ${auth-db-user}
      - key: SPRING_DATASOURCE_PASSWORD
        fromSecret: ${auth-db-pass}
    autoDeploy: false

  - type: web
    name: microservice-fleetLocation
    runtime: image
    image:
      url: docker.io/jefersonalexander/microservice-fleetlocation:latest
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URI
        value: https://discovery-server.onrender.com/eureka
      - key: SPRING_DATASOURCE_URL
        fromSecret: ${fleet-db-url}
      - key: SPRING_DATASOURCE_USERNAME
        fromSecret: ${fleet-db-user}
      - key: SPRING_DATASOURCE_PASSWORD
        fromSecret: ${fleet-db-pass}
    autoDeploy: false

  - type: web
    name: api-gateway
    runtime: image
    image:
      url: docker.io/jefersonalexander/api-gateway:latest
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: EUREKA_URI
        value: https://discovery-server.onrender.com/eureka
      - key: JWT_SECRET
        fromSecret: ${jwt-secret}
    autoDeploy: false